name: labirint
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
      - docstring-parser==0.16
      - mujoco==3.3.2
      - numpy==1.25.2
      - pyyaml==6.0.2
      - scipy==1.15.2